### ISSUE TITLE
Homepage banner photos

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#104]
Can you switch out the current homepage banner-1 photo with the Wilson Station Opening By CTA photo? ![Wilson station opening by CTA - CC BY-NC-ND 2 0](https://user-images.githubusercontent.com/84036764/120842273-7c5a4d80-c53a-11eb-8367-95478861c91e.jpeg)

**Comment by wklumpen** [comment]
Updated for v1.0.0
