### ISSUE TITLE
Potential mislabeling on the data definitions on How to Page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#110]
![image](https://user-images.githubusercontent.com/84036764/121717021-be414180-caae-11eb-8c3f-7e8613ba18c8.png)

In the data definitions section, the Measure Type for Transit Intensity is listed as Trips Per Day. In the Regional Summaries at least, the measure type for the LOS data is Trips per hour. 

Is the measure type for the LOS data in the Access download Trips per hour or trips per week?

**Comment by wklumpen** [comment]
That's a mislabel. The LOS data is average hourly trips. I'll make the update for the next fix.

**Comment by wklumpen** [comment]
Will push with final pre-launch version.
