### ISSUE TITLE
Q: Was SI Ferry mis-categorized as premium, or mislabeled?

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#112]
Another question from NYCT - the Ferry is listed as premium on the regional transit system chart. The Ferry is actually free, but if it was mis-categorized as premium, we can flag it to potentially fix in the fare calculator in the future.

**Comment by wklumpen** [comment]
I think the Ferry was free (and used as free), it's just a documentation issue. @rickl4 might be able to confirm.

**Comment by wklumpen** [comment]
Looks like all ferries were considered premium in NYC. We'll note this for future update.
