### ISSUE TITLE
Q: From our DC advocates about the DC reliability data

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#113]
From Greater Greater Washington: I thought the DC area had real time info? DC MetroHero has done a dashboard for us for DC and more recently for the region as a whole. See:
https://dcmetrohero.com/dashboard

https://metrobusreportcard.com

https://aries.dcmetrohero.com

**Comment by mlbtc** [comment]
From me: I imagine that there might have been other complications in producing reliability metrics for the DC agencies, even raw data exists. But it would be useful to name those complications, so that we can explain how DC data (and in other regions) falls short.

**Comment by aakarner** [comment]
I suspect this has to do with the necessarily limited way we were able to calculate reliability, given the varying real-time standards in use. To include on the dashboard, we would have needed DC to have a reported delay in their realtime feed.

**Comment by jamespizzurro** [comment]
Howdy y'all, Lead Developer of MetroHero here. Happy to discuss in detail how we are able to measure WMATA Metrorail and many regional bus systems' performance in real time with anyone from your end who would like to learn more, understanding that your objectives with this report were different than ours!

**Comment by wklumpen** [comment]
Hi Everyone!

Turns out the issue is much simpler than we thought: We _have_ been collecting realtime WMATA information, there was just a very small bug in the code that was not displaying it. I have made the update to the website, the on-time performance measure is now visible.

Thanks for the interest and the dashboards look great!
