### ISSUE TITLE
SF major transit lines shapefile

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#116]
A BART extension to Milpitas and the Oakland BRT aren't included in the major transit lines shapefile but should be. I requested the change back in February but I think the request got lost!
[SF_transit_lines_map.zip](https://github.com/wklumpen/equity-pulse-web/files/6771407/SF_transit_lines_map.zip)

**Comment by wklumpen** [comment]
Pushed the changes (1.0.2) to the production website.

**Comment by mlbtc** [comment]
Thank you! But the extension is a different line thickness than the rest of the major transit lines. Can you adjust the line thickness?

![image](https://user-images.githubusercontent.com/84036764/125480390-8956a982-726d-4b92-8064-276254c94a20.png)

**Comment by wklumpen** [comment]
Interesting, I don't have any control of the thickness of the lines, they should be uniform. So I'm not sure if that's a map artifact or multiple lines on top of each other.
