### ISSUE TITLE
Update How It Works page with link to extended methods

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#118]
Can you update the How it Works page as follows

How is the information shown on the Dashboard calculated?
Below, we provide a brief description of the methods used to create the dashboard. A more detailed methodology is available [here](https://transitcenter.org/wp-content/uploads/2021/07/TransitCenterEquityDashboardTechDocumentation_062421.pdf).

Accessibility represents the ease with which...

**Comment by wklumpen** [comment]
Updated with reference.
