### ISSUE TITLE
Transit Service Time Period on Dropdown is stuck on Weekday (even when Saturday data is showing)

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#119]
Due to a data error, it appears all LOS measures on a given weekday and weekend are the same. It is unclear at this point which of the two are currently represented.

Fix will require a recalculation of LOS measures.

**Comment by jamaps** [comment]
Looking into this, both were showing weekday scores (so the weekday scores should be fine, but we'll need to recompute Saturday). 

I've fixed the issue in the script, and will push an update to the other repo

**Comment by mlbtc** [comment]
It seems that new scores have been computed but the dropdown menu has a bug -- it's stuck on showing Weekday as the time period even if the map is showing Saturday data, per the URL. 

E.g. Weekday LOS - URL and Time Period on dropdown match 
![image](https://user-images.githubusercontent.com/84036764/168626977-c95d3310-cdde-452b-9fef-720db293f184.png)

Vs. Saturday LOS - URL=Saturday but Time Period on dropdown=Weekday
![image](https://user-images.githubusercontent.com/84036764/168627195-1ee91eeb-7dbc-4b0f-8bb5-7177ee85e11c.png)

**Comment by mlbtc** [comment]
NOTE: recategorized this as a priority / bug issue.

**Comment by wklumpen** [comment]
We've fixed the data issue - I created a new issue for the bug Mary found. See #145
