### ISSUE TITLE
Add video demo to How-to page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#120]
We recorded a screen-share demo showing how to use the dashboard. We'd like to add it to the How-to page. A good place for it could be at the bottom of the first section, "What does the TransitCenter Equity Dashboard Do?"

"... Data begin in February 2020 and are included for Boston, Chicago, Los Angeles, New York City, Philadelphia, San Francisco-Oakland, and Washington D.C. Learn more about how to use the Equity Dashboard with this [demo](https://vimeo.com/575112771)."

Alternatively, if you can embed the video directly on the How-to page, you could include it at or near the bottom of the page with the same caption: "Learn more about how to use the Equity Dashboard with this [demo](https://vimeo.com/575112771)."

**Comment by mlbtc** [comment]
Adding the link and text for the video demo to How-to page is still a priority, but making a video demo of how to do comparative maps is not a priority (for now)

**Comment by wklumpen** [comment]
Added embedded video - changes will be reflected in 1.2.0 release.
