### ISSUE TITLE
Reformat fares chart to emphasize gap in jobs access for people w/limited budget

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#121]
The fare chart is set up to show differences by demo groups in jobs accessible by low-cost trips vs. all trips, but there aren't significant differences by demo group in this ratio. Would be more useful to emphasize the gap in jobs that are accessible by low-cost trips only, and to remind viewers that there are differences in the total number of jobs accessible for demo group that carry over into this comparison as well.

One way to do that is to change y-axis to absolute numbers, show two data points per group: all jobs accessible & jobs accessible by low-cost trips only. A stacked bar chart could work

**Comment by mlbtc** [comment]
Would also need to adjsut the text slightly

**Comment by mlbtc** [comment]
As an example
![image](https://user-images.githubusercontent.com/84036764/131537521-9ee54d41-517d-429e-8c1d-b38bc1ec8f80.png)

**Comment by wklumpen** [comment]
I was able to reuse the code from the grouped bar chart we used for car/auto access, let me know what you think (and of course we'll need to tweak the text)

![fare_chart](https://user-images.githubusercontent.com/7478016/136965718-9c332eef-c9fd-4123-b2f7-9af648284c9f.png)

**Comment by wklumpen** [comment]
Okay here's the implementation. I have added colors and differentiated subgroups by the opacity of the bars as shown:
![fare1](https://user-images.githubusercontent.com/7478016/137345071-3e523423-2be0-4c4d-8895-dc8ad7ff01c5.png)

If you hover over a specific bar, the subtitle text updates to show the fare disparity for that group.
![fare2](https://user-images.githubusercontent.com/7478016/137345149-b6a17d33-8db7-4dfb-a7c1-c389458b5935.png)

**Comment by mlbtc** [comment]
Visual change: can you order the bars by # of jobs accessible?

**Comment by mlbtc** [comment]
Data change (if possible): can you change the metric to jobs accessible in **60 minutes** with fare budget and without, for MSA residents? Rather than jobs accessible in 45 minutes.

This suggestion came up in our briefings over the summer, particularly in regions like LA and SF where super-commuters may be taking long trips on commuter services or multiple modes.

**Comment by wklumpen** [comment]
Made the change to sorting the chart, opened a new issue for data change as it requires updating our summary data (which we are doing anyway in this data update!)
