### ISSUE TITLE
January 2021 San Francisco Data Issue

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#13]
Travel time matrices for San Francisco's January 2021 run are wonky, creating issues for Transit Service Intensity measures.

**Comment by aakarner** [comment]
There's an inconsistency with the dates in `otp_run_dates.csv` and those included in the LOS .csv files. Scores should be calculated using Jan 17 2021 as the start date but appear to use Jan 10 instead. @jamaps

**Comment by aakarner** [comment]
Resolved in most recent data push
