### ISSUE TITLE
Update fare chart text to match chart updates.

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#135]
Chart updates that were made in #121 may necessitate changes to the copy. 

The current text is below, feel free to reply with (or send along) updated text.

### How does access to opportunity shrink for transit riders with a limited transportation budget?

Many regions have a two-tiered transit system, with expensive, rapid regional transit on the one hand and affordable but slow local transit on the other. In these regions, people with low incomes are priced out of parts of the transit network, and don’t have as much access as more affluent riders.

This chart shows how access shrinks for people who can’t afford "premium" transit trips. For each group, it shows the average person’s access to jobs taking only low-cost transit trips as a share of the jobs that they could access using the entire transit network.

A value of 100% indicates that someone taking only low-cost transit trips has the same access to jobs as someone who can afford higher fares. A value of 50% indicates that someone taking only low-cost trips can access half as many jobs.

**Comment by mlbtc** [comment]
**How does access to opportunity shrink for transit riders with a limited transportation budget?**
Many regions have a two-tiered transit system, with expensive, rapid regional transit on the one hand and affordable but slow local transit on the other. In these regions, people with low incomes are priced out of parts of the transit network, and don’t have as much access as more affluent riders.

This chart shows how access shrinks for people who can’t afford "premium" transit trips. For each group, it compares the average person’s access to jobs taking only low-cost transit trips with their access to jobs using the entire transit network.

Hover over a group to learn the share of total accessible jobs that can be reached by low-cost transit trips on average. A value of 100% means that someone taking only low-cost transit trips has the same access to jobs as someone who can afford higher fares. A value of 50% means that someone taking only low-cost trips can access half as many jobs.

**Comment by wklumpen** [comment]
Great, thanks! Update will be reflected in version 1.0.1 push.
