### ISSUE TITLE
Replace NYC thumbnail on dashboard homepage

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#138]
Can you replace the current thumbnail for NYC with this picture (dropbox link: https://www.dropbox.com/s/uexil036tkkdb2p/Peter_Burka_Manhattan%20from%20Smith%20and%209th.jpg?dl=0)

and update the photo credit accordingly: NYC Homepage tile credit goes to Peter Burkas

**Comment by wklumpen** [comment]
Updated the image, will be reflected when we push v1.1.0.
