### ISSUE TITLE
Add Zero-Car Household density layer to the download center

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#139]
A user noticed that the zero-car household dot layer isn't on the download center (probably because we added that layer to the map after the other indicators). Can you add the dot layer to the download center?

And, in the meantime, could you send me a file with the dot layer, to send to the user? Thanks!

**Comment by wklumpen** [comment]
You can find the static files we serve up on the website here: https://github.com/wklumpen/equity-pulse-web/tree/master/static/data

You're looking for a file named `<region>_nocar_hhld.geojson' for whatever region you're interested in. It can be downloaded from there.

**Comment by mlbtc** [comment]
Thanks!
