### ISSUE TITLE
LA and San Francisco Evening Matrices are Too Small

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#14]
We noticed evening travel-time matrices for LA and San Francisco are oddly small for all months. Need to figure out if and how this is affecting the scores.

**Comment by aakarner** [comment]
We're chalking this up in part to BART service ending at 9pm in the Bay Area. There's also evidence that late-night service in LA was curtailed: https://abc7.com/metro-coronavirus-la-rail-service-covid19/6033565/.
