### ISSUE TITLE
Double check Chicago reliability data? [1-4h]

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#142]
Chicago bus consistently posts on-time performance of 97%, which is very high compared to other bus systems with OTP below 75%. I noticed that the Chicago reliability data is missing some fields, including the fraction of buses that had appropriate data. Is it possible that this Chicago data point is wrong?

**Comment by wklumpen** [comment]
Very possible. I can investigate

**Comment by wklumpen** [comment]
So.

It looks like the [data API](https://www.transitchicago.com/assets/1/6/cta_Bus_Tracker_API_Developer_Guide_and_Documentation_20160929.pdf) provided by CTA does not explicitly give the amount of delay for the bus, but does provide a `dly` (delay) status as True or False. My reading of the documentation is that this delay status is much more lax than the standard on-time performance approach we are using of -2 to +5 minutes. This explains why the reliability is so much higher.

It also explains why there are fields missing that are otherwise available in other fields.

Further expansion of this metric or adjustment to try and get more meaningful results is probably a v2.0 or later issue. For v1.2.0, we have two options:
* Leave it as-is
* Remove Chicago's reliability data entirely

**Comment by wklumpen** [comment]
An example of the data produced by the call to the CTA Bus API
[cta_bus.csv](https://github.com/wklumpen/equity-pulse-web/files/10148938/cta_bus.csv)

**Comment by mlbtc** [comment]
Hm... interesting, and typical! 

The story we want to emphasize for Chicago this year is "CTA reports no issues with service, even though there are clearly issues with service." The agency has been consistently dropping about 1/4 of trips but not officially changing schedules. This method of tracking OTP is clearly masking the extent of delays and fits into that story as well. 

It could be useful to preserve the data as a visual aid of the data manipulation... but only if it's possible to contextualize the data in the text immediately above with custom text on this section on the Chicago page. Here's a suggestion. I'm asking around if anyone knows how CTA defines the delay - if someone does, 

"Will your train get delayed? Do you catch an early bus so that you’re not late to work if there’s traffic? Reliability, or how well transit service adheres to the schedule, affects access to opportunity. Unreliable transit service limits access by extending travel times — whether because someone’s trip is actually delayed or because they assume it will be and build in extra time for the trip.

Buses, which often have to share street space with car traffic, are less reliable than trains, which tend to operate in dedicated rights of way. The disparity is inequitable: Bus riders are more likely than train riders to be people of color and people with low incomes.

This chart tracks transit on-time performance where data was available. For other regions on this dashboard, we defined on-time performance as the fraction of all vehicles that arrive at stops between 1 minute earlier and 5 minutes later than scheduled, which is a standard industry definition. CTA data identifies trips that were delayed but not the length of the delay; due to its near-perfect record of on-time performance, it is likely that CTA uses defines on-time trips more generously than the industry standard.

This measure does not capture canceled trips. Though rates of canceled trips have been elevated in some regions compared to 2019, most transit agencies still do not publicly report on cancellations."

If customization isn't possible then we should just remove the data & add the text on the LA, Boston, etc. pages.

**Comment by mlbtc** [comment]
UPDATE: no one knows how CTA defines the delay.

Preference is to preserve the data but add a custom disclaimer to Chicago's reliability section. Custom text is bolded.

"...This chart tracks transit on-time performance where data was available. **For other regions on this dashboard, we defined on-time performance as the fraction of all vehicles that arrives at stops between 1 minute earlier and 5 minutes later than scheduled, which is a standard industry definition. CTA data identifies delayed trips but does not provide data on the length of the delay. Due to its near-perfect on-time performance record, CTA likely defines on-time trips more liberally than the industry standard**.

This measure does not capture canceled trips. Though rates of canceled trips have been elevated in some regions compared to 2019, most transit agencies still do not publicly report on cancellations."
