### ISSUE TITLE
Aug. 2020 data not showing up on LA map [1h]

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#144]
https://dashboard.transitcenter.org/map/la?key=C000_P_c45_AM_autoN_fareN&zone=msa&date=2020-08-16&demo=none

**Comment by wklumpen** [comment]
Just saw this one! I'll dig into it.

**Comment by wklumpen** [comment]
I have identified 60 score types that appear to be missing from the dataset for this particular date, likely as a result of some of the patching we had to do. The specific `score_key` and id for that date are list in the attached CSV (for future reference).

Remedy is to load these specific scores into the database
[la_2020-08-16_missing_data_keys.csv](https://github.com/wklumpen/equity-pulse-web/files/9363898/la_2020-08-16_missing_data_keys.csv)
.

**Comment by wklumpen** [comment]
Data has been patched and updated in production database.
