### ISSUE TITLE
Tweak formatting of axes on summary page charts

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#149]
change font size or spacing of dates on summary page charts so the early months don't overlap with each other

![image](https://user-images.githubusercontent.com/84036764/203622608-3d3bb870-5f7d-4fc5-a2bd-96b52c433dfd.png)

**Comment by wklumpen** [comment]
Rotated the labels to fit a bit better - May need to discuss a longer-term version for 2.0.0. Changes will be reflected in 1.2.0
![rotated](https://user-images.githubusercontent.com/7478016/204895600-55e00025-d6ea-4e30-8774-437af9123660.png)
