### ISSUE TITLE
LA Parks Access Metric all Zeroes

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#15]
LA Parks access is currently showing a score of all zeroes. This is due to a file naming issue and will be updated in the next scores.

**Comment by jamaps** [comment]
I've recomputed all the LA scores. The park scores look good on first glance (i.e. most are at least non-zero).

**Comment by wklumpen** [comment]
Sounds good! Will close when I load the new data.

**Comment by wklumpen** [comment]
Appears to be resolved.
