### ISSUE TITLE
Adjust bin scale for map of parks access in LA? 

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#155]
A few BGs adjacent to very large parks are skewing the parks access map. Is it possible to custom-adjust the scale for the bins down so that it shows more of the variety in urbanized part of the region?

This isn't a big priority, so if it's not an easy fix, fine to address in version 2.0

![image](https://user-images.githubusercontent.com/84036764/205349090-5ebdb602-2e4d-48a9-b78f-f0634e04e3d8.png)

**Comment by wklumpen** [comment]
I think we should address our method of bins/color scaling more robustly in v2.0 at a larger level; this is a great example case though.

I will open a separate issue and reference this conversation as an example. Closing to avoid duplicate conversation.
