### ISSUE TITLE
Add disclaimers about missing data & fares to DC story page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#159]
"Note: Maryland MTA bus feeds are not included in the DC scores for 2021. This issue lowers the region's access measures for 2021, particularly in Maryland suburbs. Until it is resolved, use caution when using DC access scores from 2021." 

This could go right above the chart that shows access to jobs over time.

**Comment by mlbtc** [comment]
Editing this issue to be one disclaimer text for DC story page:

Note: Maryland MTA bus feeds are not included in the DC scores for 2021. This issue lowers the region's access measures for 2021, particularly in Maryland suburbs. Until it is resolved, use caution when using DC access scores from 2021."

The dashboard uses fare levels from 2020. Since then, WMATA lowered bus-to-rail transfer fees and rail fares on weekends and weeknights. The affordable transit access measures shown below do not reflect these policy changes. Affordable transit access scores will be updated next year to reflect the new fare policy.

**Comment by wklumpen** [comment]
Added to the dev site - will transfer over to production on update.
