### ISSUE TITLE
Update Covid cases chart to new cases/100k population

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#22]
Request to update the cases chart to normalize by population. This requires a (static) source of population.

**Comment by dana-rg** [comment]
pop estimates: https://drive.google.com/file/d/1vWQQ4-Offzao9SuJziqYrhhJqJwS4KGW/view?usp=sharing

**Comment by wklumpen** [comment]
Updated, will be reflected in next push (0.6.4-beta)
