### ISSUE TITLE
Update transit-car ratios to fixed bins

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#24]
If possible: legend for Transit-Car ratios of travel times as set, rather than percentile-based, bins: <1, <2, <3, <4, >4. I think it's easy to understand what equal travel time vs. travel time that's 4x as long means, and there is a certain value to identifying the areas that have consistently competitive transit service - as fast or faster than traveling by car.

**Comment by wklumpen** [comment]
Are we reasonably confident this will work consistently across all regions/dates? If so, I can plan to update this.

**Comment by wklumpen** [comment]
@dana-rg @aakarner I wonder if you have thoughts on this request.

**Comment by wklumpen** [comment]
I *really* don't think the primal measures will work, since they aren't normalized in any way (the ratios are somewhat). The pure scale of accessible jobs is so different in cities.

**Comment by dana-rg** [comment]
Yeah... that makes sense.  Scratch that comment.

**Comment by wklumpen** [comment]
Made the update, looks good! Will be reflected when I push v1.0.0

![fixed_ratios](https://user-images.githubusercontent.com/7478016/120818325-840cf880-c520-11eb-8cea-74248e071b24.png)
