### ISSUE TITLE
Consolidate About/Methodology/Documentation pages and update links. 

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#33]
There are currently three possible pages for documentation where there will likely be 1 to 2 at the end.
•	“About” and “Methodology” tabs have no content. These are linked in the header and also from the map “info” button.
•	Data download page has a link to a “documentation” page.
•	Story page doesn’t link to any but perhaps could link to documentation in the bottom “data” section.

**Comment by wklumpen** [comment]
Related to issue #17

**Comment by wklumpen** [comment]
I'm happy for any configuration you think best, @dana-rg - do you want to just clarify what "Pages" we have and where we should link?

There was some discussion that "About" would have the project team, while "Methodology" would have the content on methodology. Story page has notes about the story specifically.

I'll fix the broken "data download" like once we know where it might be appropriate to reference

**Comment by wklumpen** [comment]
Methodology page updated for 0.7.0
