### ISSUE TITLE
Update list of agencies and premium modes: story page and documentation page

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#44]
story page -- for each region list transit agencies included (not premium modes) and the fare cap.
documentation page -- for all regions list all agencies and premium modes. 

I'll post a file with each of these tables and send the link in Slack shortly.

**Comment by dana-rg** [comment]
- For story pages, I dropped suggested text and fare cap info for each region into a tab, and also removed the premium modes from the region-specific tabs
- For the documentation page -- I made a combined table that could be used to list all agencies and premium modes in the endnote.
File is here [https://docs.google.com/spreadsheets/d/1Kea1kXJGpU-oBbN3w4KBFVw9hUOiajtFZe74v1uc12U/edit#gid=0]

**Comment by wklumpen** [comment]
I think this has been resolved and will stay as-is. Feel free to re-open if I'm forgetting something 😄

**Comment by dana-rg** [comment]
I think this is OK to leave as is with the low-fare definition at the bottom, but one more clarification in the copy by the low-fare graph on the story page would help with accuracy about how the premium modes are used. In principle a low-fare trip could occur on the premium network, so its not that we excluded the network for ALL low-fare trips. 
Proposed text: 

> This chart shows how access shrinks for people who can’t afford high-cost trips. It compares the number of jobs accessible taking only low-cost transit trips, compared to traveling on the entire transit network, including more expensive trips.

Current text: 

> This chart shows how access shrinks for people who can’t afford high-cost **modes**. It compares the number of jobs accessible taking only low-cost transit trips, compared to traveling on the entire transit network, including expensive **“premium” service**.

**Comment by wklumpen** [comment]
Made the changes to that part of the text, we've resolved the design of the premium routes.
