### ISSUE TITLE
Match story page links and header text

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#46]
On the story page - should the headings match the links on the "Just to a Section" menu on the RHS in terms of phrasing and capitalization?
- Access to destination on transit [links to] Access to Destinations on Transit
- Transit service levels [links to]  Transit Service Intensity
- Transit fares and access [links to]  Fares
- Traveling by transit vs. car [links to]  Car Access
- Transit reliability [links to]  Reliability [this link still isn't working for me, maybe that's in the next update .]

**Comment by wklumpen** [comment]
Made these changes, will be reflected in next push, along with the reliability fix (0.6.4-beta)
