### ISSUE TITLE
Make regional picture & region name on homepage link to region's story page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#47]
Several of our TC testers instinctively clicked on the picture & the region name and were flustered when that didn't take them anywhere. At the same time, we want to funnel users to the Story page first, as an introduction for major trends/takeaways to look out for in the map and data download page.

To address two issues at once, could we make the picture & the region name link directly to the Story page for that region?

**Comment by wklumpen** [comment]
We had an internal discussion about that and couldn't decide if it was misleading to make a design choice for that. If you're okay with the default going to the story, I'll make that update.

**Comment by wklumpen** [comment]
Updated, look for once 0.6.4-beta is pushed.
