### ISSUE TITLE
Adjusting format of clickable date labels

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#48]
We'd like to make the clickable feature of the dates even more obvious on the interactive charts, if possible. We generated a few ideas - are either of these possible? 
1) adding a hover feature over the interactive dates with a note like "Click on a date to show its data on the right bar chart" (like the hover labels over the regional profiles on the homepage) 
2) enlarging and/or bolding the font size of the date labels.

**Comment by wklumpen** [comment]
Number 1 is a feature of Materialize (the CSS package I'm using), and it may not work well with the d3 package we're using for charts. 

I need a little bit more clarification on the behaviour for No. 1: Would the tooltip with the message only show when the date is hovered over?

One middle ground here is to make it so when the dates (and bars) are hovered over they respond in some way (perhaps by getting slightly bigger or darker) to guide the idea that it will respond to a click. That may be a bit nicer than having a tooltip pop up which may interfere with the data viewing

**Comment by mlbtc** [comment]
I like your middle ground idea. We could keep the note below the chart about the dates and bars being clickable, and then have the dates & bars respond when they are hovered over. Bigger or darker would work - whichever you think looks better.

Can you change the note about the interaction to "This chart is interactive. Change the data on the right bar chart by clicking a different date or the gray bar below."

**Comment by wklumpen** [comment]
Yes, though I will make a small modification to say "above", unless you'd like the text placed on top of the chart?

**Comment by wklumpen** [comment]
Oh, I see where the "below" comes from! Got it, will make updates.

**Comment by mlbtc** [comment]
Maybe it could be "This chart is interactive. Change the data on the right bar chart by clicking a different date or a gray bar"

**Comment by wklumpen** [comment]
Updated, will be reflected in the next push. Changes made:

- Bars turn to the blue color (same as the navbar) when hovered over, with some opacity so it's not overwhelming
- Dates turn to the blue color and are bolded when hovered over
- All items are reset when the mouse leaves the feature

**Comment by mlbtc** [comment]
The date labels are just going blue when you hover over them - not also getting bolder. Can you add or strengthen the emboldening feature?
