### ISSUE TITLE
Set starting zoom levels and lat/lon for all regions

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#52]
Update the zoom levels and starting lat/lon for all regions to center on the urban core definition, and fit relatively well on a normal-sized screen.

**Comment by mlbtc** [comment]
I like what you've suggested - center urban core, zoom out to fit on a normal-sized (e.g. laptop, in these Covid days) screen

**Comment by wklumpen** [comment]
Updates made for a low-res laptop screen (1366x768).
