### ISSUE TITLE
Round all chart figures to whole number on Story page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#54]
A few examples I've found of decimals on the charts page - Travel time is rounded to the hundredth on the travel to grocery stores chart in NYC. Trips per hour rounded to the hundredth on the LA service intensity chart

**Comment by wklumpen** [comment]
Changed to the following number styling:

- Greater or equal to 1,000 -> Comma styling
- Less than 1000, rounded to nearest integer
