### ISSUE TITLE
Potential buggy result in BG 060133551121

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#59]
BG 060133551121 (in Bay Area, between Brentwood & Livermore) is a large rural area that's showing up as having access to 7641 jobs (other areas around it have access to 0 jobs by transit). Could this be a bug?

**Comment by wklumpen** [comment]
Let's see if things are improved once we update the data this week.

**Comment by aakarner** [comment]
I suspect this is due to the centroid location and snapping to the pedestrian network. There's no reason why a single block group origin would generate erroneous travel times to destinations.
