### ISSUE TITLE
Transit service in SF MSA only showing 20-100% percentiles

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#60]
Not seeing any bottom 20% BGs

**Comment by aakarner** [comment]
This is still an issue in the most recent data update.

![image](https://user-images.githubusercontent.com/4266553/119689705-ae6b0180-be0e-11eb-98f2-fdff45e3b54d.png)

**Comment by wklumpen** [comment]
This is likely due to the fact that there are too many zeroes (more than 20% of the data). Can we confirm this with the raw LOS scores?

**Comment by aakarner** [comment]
Confirmed - these are Chicago data but it will be the same elsewhere:

Histogram
![image](https://user-images.githubusercontent.com/4266553/119986031-fdd53d00-bf88-11eb-9664-ddd8a6d38196.png)

Quantiles
![image](https://user-images.githubusercontent.com/4266553/119986250-3aa13400-bf89-11eb-9531-4b1e53091c66.png)
