### ISSUE TITLE
Add Geo identifiers to data download

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#64]
Could you add fields that identify each block group as being a part of or not a part of each type of geography? E.g. MSA, Economic Region, Urban Core, Equity Neighborhood. Something like: Field = MSA. Value 1 = part of MSA, Value 0 = not a part of the MSA

**Comment by wklumpen** [comment]
I'm going to shelve this for now as I focus on some of the other bugs, as it's a bit of a lift. There's already a fair bit of data adjustment going on behind the scenes for the downloads.

Alternative: Provide a separate mapping file for a region containing the data you're suggesting. People can join it in as they wish.

**Comment by mlbtc** [comment]
If providing the separate mapping file is easy to do, that would be fine.
