### ISSUE TITLE
Fare constraint chart data caption needs to be updated

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#65]
The data caption says: data for weekdays 7am-9am or 10pm-12am (weeknights) in REGION as of the week of DATE. 

Were we going to include weeknight travelers on this chart? If not, we can update the label just to say "data for weekdays 7am-9am in REGION MSA as of the week of DATE."

**Comment by wklumpen** [comment]
Good catch. Will be reflected in 0.7.0-beta.
