### ISSUE TITLE
Minor text edit: author alphabetization

### ISSUE THREAD

**Issue by dana-rg** [wklumpen/equity-pulse-web#70]
Reorder Da Silva alphabetically in two spots on the "How it Works" page: 
- "Who made the Dashboard" between Allen and Farber (unless you're doing with Silva and then its OK)
- How do I cite this Dashboard -- between Allen and Li (unless you're doing Silva, and then its after Robinson)
- I dropped a comment in the TF manuscript in overleaf to move it depending on if you're going by D or S, I think it'd be the D.

**Comment by wklumpen** [comment]
Confirmed with Diego that it's an "S" name, have done the reordering for 0.7.1-beta release.
