### ISSUE TITLE
Change Tab title for "How it Works" page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#72]
When you open the "how it works" page, the tab title on my browser says "Transit Scorecard - TransitCenter Equity Dashboard." Can you change it so that it's labeled as "How it Works - TransitCenter Equity Dashboard" ?

Same issue and request to change for each region's Data download pages.

**Comment by wklumpen** [comment]
Will be updated in 0.7.1-beta.
