### ISSUE TITLE
Enlarge font size of labels on Maps

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#73]
Font size on the Map page should be a bit bigger. The legend & the timeline font needs to increase a few sizes. The text of the captions on the left side bar could probably increase 1 size or so.

**Comment by wklumpen** [comment]
I can enlarge them a little, however I did find that it starts to crowd the map a fair bit. Will make the update and see how it looks.

**Comment by wklumpen** [comment]
Pushed things to be a little bigger. Will be reflected in 0.7.1-beta
