### ISSUE TITLE
Question about on-time performance & MUNI's headway-based schedules

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#80]
MUNI switched to headway-based bus dispatching, from scheduled-based, at the beginning of the pandemic. Is our OTP measurement taking that into consideration, or is it measuring based on a schedule? If we can't model reliability based on headways, we should probably just remove the MUNI bus reliability data

**Comment by wklumpen** [comment]
So then we'll just show the other two?

**Comment by dana-rg** [comment]
I think this is OK -- if MUNI reports they are late, that's what we report.
