### ISSUE TITLE
Make MSA the default region again

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#83]
Sorry, I requested the change to urban core but you had it right the first time. if it's an easy change to make, could you change it back? 

Better to start big and allow people to narrow if they want - Advocates pointed out that they didn't realize there was more data at first.

**Comment by wklumpen** [comment]
Updated for 0.7.1-beta

If you can, please comment on issue #52 on how "zoomed out" you'd like to start (data should be zoomed out but fill large screen, or entire region should be visible)
