### ISSUE TITLE
Typo in Story Page under "Change Service and Focus Development to Reduce Access Gaps" section

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#84]
Text shows up as this, but you can delete the first "Example: Los Angeles’s Transit-Oriented Communities"

Coordinating land use and transit investments: Support the development of jobs and affordable housing near frequent transit lines. Example: Los Angeles’s Transit-Oriented Communities
Example: Los Angeles’s Transit-Oriented Communities program has produced 7,000 affordable housing units near transit through fall 2020.

**Comment by wklumpen** [comment]
Good catch. Fixed it, should be live.
