### ISSUE TITLE
Create 6th banner image for all regions

### ISSUE THREAD

**Issue by wklumpen** [wklumpen/equity-pulse-web#88]
The images should have the following format:

* 1920x400 pixels
* Files should be named `banner-6.jpg` (note file format) and put in individual folders for each region (boston, chicago, dc, nyc, philadelphia, la, and sf)

**Comment by mlbtc** [comment]
@wklumpen I've saved banner-6 photos in each of the 7 folders.

I've also suggested a few new banner photos to replace ones that show up blurry on the website, creating new issues to explain each of those.
