### ISSUE TITLE
Question: about job access by car # on Story page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#89]
What is the region that you used for the the "average job access by cars" that have been added to each of the Story pages?

I used the MSA for my estimates that I included on the Additions to Regional story Page google doc. Did you use the Urban core (which would be ideal?)

I'm wondering why the numbers are so different.
E.g. Washington DC -- my estimate was 1,053,524 but yours is 1,931,451

**Comment by mlbtc** [comment]
I've figured it out - the numbers added to the story page are the urban core residents' average access to jobs.

**Comment by wklumpen** [comment]
Was just about to type this! :)

**Comment by wklumpen** [comment]
For posterity, the calculation is as follows:

T = `C000_P_c45_AM_autoN_fareN` in the `urban` region for population group `pop_total`
Q = `C000_P_c45_AM_autoY_fareN` in the `urban` region for population group `pop_total`

Since Q is the Transit:Auto ratio, auto access is calculated as  T*(1/Q)
