### ISSUE TITLE
Missing period on Story page

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#90]
Remove 
<For each of the following categories, it shows the average travel time by car or transit: the nearest hospital, urgent care facility, and college/university, and the third-nearest grocery store and pharmacy>
replace with 
<For each of the following categories, it shows the average travel time by car or transit: the nearest hospital, urgent care facility, and college/university, and the third-nearest grocery store and pharmacy.>"

**Comment by wklumpen** [comment]
Change made for v1.0.0
