### ISSUE TITLE
DC Thumbnail photo

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#91]
Adjust the photo so that the bus isn't cut off (it's ok if the Washington monument is instead). 

Bummer that the photo is just not quite sized the right way!

**Comment by wklumpen** [comment]
Yeah, I felt odd cutting off the monument, but alas it's just not quite right.

Perhaps there's a different DC photo? Otherwise sure, I can resize it.

**Comment by mlbtc** [comment]
I'd say resize. Hayley applied a certain filter to all of the thumbnail photos and is out on vacation for a few weeks now -- I don't want the DC thumbnail to look different from the others because it doesn't have a filter

**Comment by wklumpen** [comment]
Made the resize, look for it when I push v1.0.0
