### ISSUE TITLE
Question: Why did the access numbers (+ charts) all change slightly since the last update?

### ISSUE THREAD

**Issue by mlbtc** [wklumpen/equity-pulse-web#92]
Was it because of various bugs/data issues that have now been smoothed out? Should we expect any more changes to the data points before launch? 

We are preparing regional factsheets using elements of the story page, and ideally the factsheets will match what's on the website when we launch.

Ex of the slight changes: access to jobs in 45 minutes by transit for Boston urban core on Feb. 21 was 207,168 in the old update. Now it's showing up as 246,205

**Comment by aakarner** [comment]
We identified a quality control issue while working with the prior dataset that necessitated recalculating all weekday travel time matrices. The most recent access numbers and charts are based on these new matrices and will not change further. You can safely generate regional factsheets based them.
